name: Android CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'
        
    - name: Grant execute permission for gradlew
      run: chmod +x ./app/gradlew
    - name: Build with Gradle
      run: ./app/gradlew build
    - uses: actions/upload-artifact@v1
      with:
        name: my-artifact
        path: ./app/app/build/outputs/apk/debug/app-debug.apk
